repos:
- repo: local
  hooks:
    - id: update_requirements
      name: updating_requirements.txt
      entry: bash -c "python3 -m  pipreqs.pipreqs . --force"
      language: system
      types: [python]
      pass_filenames: false

- repo: local
  hooks:
    - id: update_torchvision
      name: update_torchvision_version
      entry: bash -c "sed -i -e 's/torchvision==0.14.0/torchvision==0.13.1/g' requirements.txt"
      language: system
      types: [python]
      pass_filenames: false

- repo: local
  hooks:
    - id: updating_environment_file
      name: update_conda_environment
      entry: bash -c "conda env update --prefix ./env --file hispatologic_cancer_environment.yml  --prune"
      language: system
      types: [python]
      pass_filenames: false
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      args: # arguments to configure flake8
        # making isort line length compatible with black
        - "--max-line-length=88"
        - "--ignore=W503,E402,E722,F403,F405, E302"
