image_size : 32
batch_size : 200
n_classes : 2
learning_rate : 0.0001
weight_decay : 0.0001
num_epochs : 10
patch_size : 7  # Size of the patches to be extract from the input images
projection_dim : 64
num_heads : 4
transformer_layers : 8
mlp_head_units : [56, 28]