image_size : 20
batch_size : 200
n_classes : 2
learning_rate : 0.0001
weight_decay : 0.0001
num_epochs : 1
patch_size : 7  # Size of the patches to be extract from the input images
projection_dim : 64
num_heads : 4
transformer_layers : 8
mlp_head_units : [56, 28]
save_model_path : "model_save_load/transformer_model.h5"